use crate::proc::{CaseInsensitiveKeywordSet, KeywordSet};
use crate::racy_lock::RacyLock;

/// C++ reserved keywords and identifiers that cannot be used as variable names
pub const RESERVED_KEYWORDS: &[&str] = &[
    // C++ keywords
    "alignas",
    "alignof",
    "and",
    "and_eq",
    "asm",
    "auto",
    "bitand",
    "bitor",
    "bool",
    "break",
    "case",
    "catch",
    "char",
    "char8_t",
    "char16_t",
    "char32_t",
    "class",
    "compl",
    "concept",
    "const",
    "consteval",
    "constexpr",
    "constinit",
    "const_cast",
    "continue",
    "co_await",
    "co_return",
    "co_yield",
    "decltype",
    "default",
    "delete",
    "do",
    "double",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "export",
    "extern",
    "false",
    "float",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "not",
    "not_eq",
    "nullptr",
    "operator",
    "or",
    "or_eq",
    "private",
    "protected",
    "public",
    "reflexpr",
    "register",
    "reinterpret_cast",
    "requires",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "static_cast",
    "struct",
    "switch",
    "template",
    "this",
    "thread_local",
    "throw",
    "true",
    "try",
    "typedef",
    "typeid",
    "typename",
    "union",
    "unsigned",
    "using",
    "virtual",
    "void",
    "volatile",
    "wchar_t",
    "while",
    "xor",
    "xor_eq",
    // Common standard library identifiers to avoid conflicts
    "std",
    "string",
    "vector",
    "array",
    "map",
    "set",
    "list",
    "pair",
    "tuple",
    "function",
    "bind",
    "shared_ptr",
    "unique_ptr",
    "weak_ptr",
    "nullptr_t",
    "size_t",
    "ptrdiff_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
];

/// The above keywords as a cached case-sensitive set.
pub static RESERVED_SET: RacyLock<KeywordSet> =
    RacyLock::new(|| KeywordSet::from_iter(RESERVED_KEYWORDS.iter().copied()));

/// The above keywords as a cached case-insensitive set.
pub static RESERVED_CASE_INSENSITIVE_SET: RacyLock<CaseInsensitiveKeywordSet> =
    RacyLock::new(|| CaseInsensitiveKeywordSet::from_iter(RESERVED_KEYWORDS.iter().copied()));

/// Prefixes we avoid when generating identifiers.
pub const RESERVED_PREFIXES: &[&str] = &["_naga"];
